/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MesCommandesRouteImport } from './routes/mes-commandes'
import { Route as MerciRouteImport } from './routes/merci'
import { Route as MentionsRouteImport } from './routes/mentions'
import { Route as GarantieRouteImport } from './routes/garantie'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiAdminMeRouteImport } from './routes/api/admin/me'
import { Route as ApiAdminReviewsIndexRouteImport } from './routes/api/admin/reviews/index'
import { Route as ApiAdminOrdersIndexRouteImport } from './routes/api/admin/orders/index'
import { Route as ApiAdminReviewsActionRouteImport } from './routes/api/admin/reviews/action'
import { Route as ApiAdminOrdersUpdateRouteImport } from './routes/api/admin/orders/update'

const MesCommandesRoute = MesCommandesRouteImport.update({
  id: '/mes-commandes',
  path: '/mes-commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciRoute = MerciRouteImport.update({
  id: '/merci',
  path: '/merci',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsRoute = MentionsRouteImport.update({
  id: '/mentions',
  path: '/mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const GarantieRoute = GarantieRouteImport.update({
  id: '/garantie',
  path: '/garantie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMeRoute = ApiAdminMeRouteImport.update({
  id: '/api/admin/me',
  path: '/api/admin/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReviewsIndexRoute = ApiAdminReviewsIndexRouteImport.update({
  id: '/api/admin/reviews/',
  path: '/api/admin/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersIndexRoute = ApiAdminOrdersIndexRouteImport.update({
  id: '/api/admin/orders/',
  path: '/api/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReviewsActionRoute = ApiAdminReviewsActionRouteImport.update({
  id: '/api/admin/reviews/action',
  path: '/api/admin/reviews/action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersUpdateRoute = ApiAdminOrdersUpdateRouteImport.update({
  id: '/api/admin/orders/update',
  path: '/api/admin/orders/update',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/garantie': typeof GarantieRoute
  '/mentions': typeof MentionsRoute
  '/merci': typeof MerciRoute
  '/mes-commandes': typeof MesCommandesRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/orders/update': typeof ApiAdminOrdersUpdateRoute
  '/api/admin/reviews/action': typeof ApiAdminReviewsActionRoute
  '/api/admin/orders/': typeof ApiAdminOrdersIndexRoute
  '/api/admin/reviews/': typeof ApiAdminReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/garantie': typeof GarantieRoute
  '/mentions': typeof MentionsRoute
  '/merci': typeof MerciRoute
  '/mes-commandes': typeof MesCommandesRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/orders/update': typeof ApiAdminOrdersUpdateRoute
  '/api/admin/reviews/action': typeof ApiAdminReviewsActionRoute
  '/api/admin/orders': typeof ApiAdminOrdersIndexRoute
  '/api/admin/reviews': typeof ApiAdminReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/garantie': typeof GarantieRoute
  '/mentions': typeof MentionsRoute
  '/merci': typeof MerciRoute
  '/mes-commandes': typeof MesCommandesRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/orders/update': typeof ApiAdminOrdersUpdateRoute
  '/api/admin/reviews/action': typeof ApiAdminReviewsActionRoute
  '/api/admin/orders/': typeof ApiAdminOrdersIndexRoute
  '/api/admin/reviews/': typeof ApiAdminReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cgv'
    | '/confidentialite'
    | '/contact'
    | '/garantie'
    | '/mentions'
    | '/merci'
    | '/mes-commandes'
    | '/api/checkout'
    | '/api/stripe-webhook'
    | '/api/admin/me'
    | '/api/admin/orders/update'
    | '/api/admin/reviews/action'
    | '/api/admin/orders/'
    | '/api/admin/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cgv'
    | '/confidentialite'
    | '/contact'
    | '/garantie'
    | '/mentions'
    | '/merci'
    | '/mes-commandes'
    | '/api/checkout'
    | '/api/stripe-webhook'
    | '/api/admin/me'
    | '/api/admin/orders/update'
    | '/api/admin/reviews/action'
    | '/api/admin/orders'
    | '/api/admin/reviews'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cgv'
    | '/confidentialite'
    | '/contact'
    | '/garantie'
    | '/mentions'
    | '/merci'
    | '/mes-commandes'
    | '/api/checkout'
    | '/api/stripe-webhook'
    | '/api/admin/me'
    | '/api/admin/orders/update'
    | '/api/admin/reviews/action'
    | '/api/admin/orders/'
    | '/api/admin/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CgvRoute: typeof CgvRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  GarantieRoute: typeof GarantieRoute
  MentionsRoute: typeof MentionsRoute
  MerciRoute: typeof MerciRoute
  MesCommandesRoute: typeof MesCommandesRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiAdminMeRoute: typeof ApiAdminMeRoute
  ApiAdminOrdersUpdateRoute: typeof ApiAdminOrdersUpdateRoute
  ApiAdminReviewsActionRoute: typeof ApiAdminReviewsActionRoute
  ApiAdminOrdersIndexRoute: typeof ApiAdminOrdersIndexRoute
  ApiAdminReviewsIndexRoute: typeof ApiAdminReviewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mes-commandes': {
      id: '/mes-commandes'
      path: '/mes-commandes'
      fullPath: '/mes-commandes'
      preLoaderRoute: typeof MesCommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci': {
      id: '/merci'
      path: '/merci'
      fullPath: '/merci'
      preLoaderRoute: typeof MerciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions': {
      id: '/mentions'
      path: '/mentions'
      fullPath: '/mentions'
      preLoaderRoute: typeof MentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garantie': {
      id: '/garantie'
      path: '/garantie'
      fullPath: '/garantie'
      preLoaderRoute: typeof GarantieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/me': {
      id: '/api/admin/me'
      path: '/api/admin/me'
      fullPath: '/api/admin/me'
      preLoaderRoute: typeof ApiAdminMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reviews/': {
      id: '/api/admin/reviews/'
      path: '/api/admin/reviews'
      fullPath: '/api/admin/reviews/'
      preLoaderRoute: typeof ApiAdminReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders/': {
      id: '/api/admin/orders/'
      path: '/api/admin/orders'
      fullPath: '/api/admin/orders/'
      preLoaderRoute: typeof ApiAdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reviews/action': {
      id: '/api/admin/reviews/action'
      path: '/api/admin/reviews/action'
      fullPath: '/api/admin/reviews/action'
      preLoaderRoute: typeof ApiAdminReviewsActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders/update': {
      id: '/api/admin/orders/update'
      path: '/api/admin/orders/update'
      fullPath: '/api/admin/orders/update'
      preLoaderRoute: typeof ApiAdminOrdersUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CgvRoute: CgvRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  GarantieRoute: GarantieRoute,
  MentionsRoute: MentionsRoute,
  MerciRoute: MerciRoute,
  MesCommandesRoute: MesCommandesRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiAdminMeRoute: ApiAdminMeRoute,
  ApiAdminOrdersUpdateRoute: ApiAdminOrdersUpdateRoute,
  ApiAdminReviewsActionRoute: ApiAdminReviewsActionRoute,
  ApiAdminOrdersIndexRoute: ApiAdminOrdersIndexRoute,
  ApiAdminReviewsIndexRoute: ApiAdminReviewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
