/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MesCommandesRouteImport } from './routes/mes-commandes'
import { Route as MerciRouteImport } from './routes/merci'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'

const MesCommandesRoute = MesCommandesRouteImport.update({
  id: '/mes-commandes',
  path: '/mes-commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciRoute = MerciRouteImport.update({
  id: '/merci',
  path: '/merci',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/merci': typeof MerciRoute
  '/mes-commandes': typeof MesCommandesRoute
  '/api/checkout': typeof ApiCheckoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/merci': typeof MerciRoute
  '/mes-commandes': typeof MesCommandesRoute
  '/api/checkout': typeof ApiCheckoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/merci': typeof MerciRoute
  '/mes-commandes': typeof MesCommandesRoute
  '/api/checkout': typeof ApiCheckoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/merci' | '/mes-commandes' | '/api/checkout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/merci' | '/mes-commandes' | '/api/checkout'
  id: '__root__' | '/' | '/merci' | '/mes-commandes' | '/api/checkout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MerciRoute: typeof MerciRoute
  MesCommandesRoute: typeof MesCommandesRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mes-commandes': {
      id: '/mes-commandes'
      path: '/mes-commandes'
      fullPath: '/mes-commandes'
      preLoaderRoute: typeof MesCommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci': {
      id: '/merci'
      path: '/merci'
      fullPath: '/merci'
      preLoaderRoute: typeof MerciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MerciRoute: MerciRoute,
  MesCommandesRoute: MesCommandesRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
